-- Seed script to populate database with sample users for testing matches
-- Run this after the main database.sql and migrations

USE thursdate;

-- Insert sample users with complete profile data
-- Password for all users: "password123" (hashed with bcrypt)

INSERT INTO users (
  email, 
  password, 
  first_name, 
  last_name, 
  gender, 
  dob, 
  current_location,
  from_location,
  profile_pic_url,
  height,
  relationship_status,
  pets,
  drinking,
  smoking,
  food_preference,
  religious_level,
  kids_preference,
  favourite_travel_destination,
  interests,
  instagram,
  linkedin,
  face_photos,
  intent,
  onboarding_complete,
  approval
) VALUES 
(
  'sarah.johnson@example.com',
  '$2b$10$xQqVZ8K3lXKJ4X8vZ9xW5eF.WxJhZ6KpY9qHxW5eF.WxJhZ6KpY9q',
  'Sarah',
  'Johnson',
  'Female',
  '1998-03-15',
  'Bangalore',
  'Mumbai',
  'https://randomuser.me/api/portraits/women/1.jpg',
  165,
  'Single',
  'Love Dogs',
  'Socially',
  'No',
  'Vegetarian',
  'Not Religious',
  'Want Someday',
  'Japan',
  '["Photography", "Hiking", "Coffee", "Travel", "Reading"]',
  '@sarah_adventures',
  'https://linkedin.com/in/sarahjohnson',
  '["https://randomuser.me/api/portraits/women/1.jpg", "https://randomuser.me/api/portraits/women/11.jpg", "https://randomuser.me/api/portraits/women/21.jpg"]',
  '{"bio": "Love exploring new cafes and hiking trails on weekends. Always up for deep conversations over coffee ☕", "lifestyleImageUrls": ["https://images.unsplash.com/photo-1469474968028-56623f02e42e", "https://images.unsplash.com/photo-1506905925346-21bda4d32df4", "https://images.unsplash.com/photo-1445905595283-21f8ae8a33d2"], "profileQuestions": {"jobTitle": "Product Designer", "companyName": "Tech Startup", "education": "MIT", "educationLevel": "Masters", "sleepSchedule": "Early Bird", "dateBill": "Split the bill", "relationshipValues": ["Honesty", "Communication"], "religion": "Agnostic", "livingSituation": "Renting", "languages": ["English", "Hindi", "Spanish"]}, "movies": ["Inception", "La La Land", "The Grand Budapest Hotel"], "tvShows": ["Breaking Bad", "The Crown"], "artistsBands": ["Coldplay", "Taylor Swift"], "watchList": ["The Matrix", "Parasite"]}',
  true,
  true
),
(
  'alex.chen@example.com',
  '$2b$10$xQqVZ8K3lXKJ4X8vZ9xW5eF.WxJhZ6KpY9qHxW5eF.WxJhZ6KpY9q',
  'Alex',
  'Chen',
  'Male',
  '1996-07-22',
  'Mumbai',
  'Delhi',
  'https://randomuser.me/api/portraits/men/1.jpg',
  178,
  'Single',
  'Have Cats',
  'Often',
  'No',
  'Non-Vegetarian',
  'Moderately Religious',
  'Want Someday',
  'Italy',
  '["Coding", "Cooking", "Gaming", "Fitness", "Travel"]',
  '@alex_chen_dev',
  'https://linkedin.com/in/alexchen',
  '["https://randomuser.me/api/portraits/men/1.jpg", "https://randomuser.me/api/portraits/men/11.jpg", "https://randomuser.me/api/portraits/men/21.jpg"]',
  '{"bio": "Tech enthusiast by day, amateur chef by night. Looking for someone to share adventures with 🌍", "lifestyleImageUrls": ["https://images.unsplash.com/photo-1504674900247-0877df9cc836", "https://images.unsplash.com/photo-1517836357463-d25dfeac3438", "https://images.unsplash.com/photo-1511379938547-c1f69419868d"], "profileQuestions": {"jobTitle": "Software Engineer", "companyName": "Google", "education": "IIT Delhi", "educationLevel": "Bachelors", "sleepSchedule": "Night Owl", "dateBill": "I will pay", "relationshipValues": ["Trust", "Adventure"], "religion": "Buddhist", "livingSituation": "Own Place", "languages": ["English", "Mandarin", "Hindi"]}, "movies": ["The Matrix", "Interstellar", "Blade Runner"], "tvShows": ["Stranger Things", "Black Mirror"], "artistsBands": ["The Weeknd", "Daft Punk"], "watchList": ["Dune", "Avatar 2"]}',
  true,
  true
),
(
  'priya.sharma@example.com',
  '$2b$10$xQqVZ8K3lXKJ4X8vZ9xW5eF.WxJhZ6KpY9qHxW5eF.WxJhZ6KpY9q',
  'Priya',
  'Sharma',
  'Female',
  '1997-11-08',
  'Delhi',
  'Jaipur',
  'https://randomuser.me/api/portraits/women/2.jpg',
  160,
  'Single',
  'No Pets',
  'Never',
  'No',
  'Vegetarian',
  'Deeply Religious',
  'Want Many',
  'Paris',
  '["Yoga", "Dancing", "Painting", "Music", "Meditation"]',
  '@priya.art',
  'https://linkedin.com/in/priyasharma',
  '["https://randomuser.me/api/portraits/women/2.jpg", "https://randomuser.me/api/portraits/women/12.jpg", "https://randomuser.me/api/portraits/women/22.jpg"]',
  '{"bio": "Artist and yoga instructor finding balance in life. Love creating art and spreading positive vibes ✨", "lifestyleImageUrls": ["https://images.unsplash.com/photo-1544367567-0f2fcb009e0b", "https://images.unsplash.com/photo-1506126613408-eca07ce68773", "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b"], "profileQuestions": {"jobTitle": "Yoga Instructor", "companyName": "Self Employed", "education": "Delhi University", "educationLevel": "Bachelors", "sleepSchedule": "Early Bird", "dateBill": "Split the bill", "relationshipValues": ["Spirituality", "Kindness"], "religion": "Hindu", "livingSituation": "With Family", "languages": ["Hindi", "English"]}, "movies": ["Eat Pray Love", "The Notebook", "Amelie"], "tvShows": ["Friends", "Modern Family"], "artistsBands": ["Adele", "Ed Sheeran"], "watchList": ["La La Land", "The Greatest Showman"]}',
  true,
  true
),
(
  'rahul.verma@example.com',
  '$2b$10$xQqVZ8K3lXKJ4X8vZ9xW5eF.WxJhZ6KpY9qHxW5eF.WxJhZ6KpY9q',
  'Rahul',
  'Verma',
  'Male',
  '1995-05-30',
  'Bangalore',
  'Pune',
  'https://randomuser.me/api/portraits/men/2.jpg',
  182,
  'Single',
  'Love Dogs',
  'Socially',
  'Occasionally',
  'Non-Vegetarian',
  'Not Religious',
  'Open to Kids',
  'New York',
  '["Sports", "Photography", "Cricket", "Music", "Traveling"]',
  '@rahul_captures',
  'https://linkedin.com/in/rahulverma',
  '["https://randomuser.me/api/portraits/men/2.jpg", "https://randomuser.me/api/portraits/men/12.jpg", "https://randomuser.me/api/portraits/men/22.jpg"]',
  '{"bio": "Sports enthusiast and photographer. Believer in living life to the fullest! 📸⚽", "lifestyleImageUrls": ["https://images.unsplash.com/photo-1452626038306-9aae5e071dd3", "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7", "https://images.unsplash.com/photo-1496181133206-80ce9b88a853"], "profileQuestions": {"jobTitle": "Marketing Manager", "companyName": "Amazon", "education": "Symbiosis", "educationLevel": "MBA", "sleepSchedule": "Flexible", "dateBill": "I will pay", "relationshipValues": ["Fun", "Loyalty"], "religion": "Agnostic", "livingSituation": "Renting", "languages": ["English", "Hindi", "Marathi"]}, "movies": ["The Shawshank Redemption", "The Dark Knight", "Forrest Gump"], "tvShows": ["Game of Thrones", "The Office"], "artistsBands": ["Imagine Dragons", "Linkin Park"], "watchList": ["Oppenheimer", "Mission Impossible"]}',
  true,
  true
),
(
  'ananya.kapoor@example.com',
  '$2b$10$xQqVZ8K3lXKJ4X8vZ9xW5eF.WxJhZ6KpY9qHxW5eF.WxJhZ6KpY9q',
  'Ananya',
  'Kapoor',
  'Female',
  '1999-01-12',
  'Mumbai',
  'Mumbai',
  'https://randomuser.me/api/portraits/women/3.jpg',
  168,
  'Single',
  'Have Cats',
  'Often',
  'No',
  'Vegan',
  'Not Religious',
  'Do Not Want',
  'Bali',
  '["Fashion", "Blogging", "Fitness", "Shopping", "Food"]',
  '@ananya_style',
  'https://linkedin.com/in/ananyakapoor',
  '["https://randomuser.me/api/portraits/women/3.jpg", "https://randomuser.me/api/portraits/women/13.jpg", "https://randomuser.me/api/portraits/women/23.jpg"]',
  '{"bio": "Fashion blogger and fitness enthusiast. Living my best life one outfit at a time! 👗💪", "lifestyleImageUrls": ["https://images.unsplash.com/photo-1483985988355-763728e1935b", "https://images.unsplash.com/photo-1540553016722-983e48a2cd10", "https://images.unsplash.com/photo-1490645935967-10de6ba17061"], "profileQuestions": {"jobTitle": "Fashion Blogger", "companyName": "Self Employed", "education": "NIFT", "educationLevel": "Bachelors", "sleepSchedule": "Night Owl", "dateBill": "Split the bill", "relationshipValues": ["Independence", "Style"], "religion": "Atheist", "livingSituation": "Own Place", "languages": ["English", "Hindi", "French"]}, "movies": ["The Devil Wears Prada", "Clueless", "Breakfast at Tiffanys"], "tvShows": ["Gossip Girl", "Emily in Paris"], "artistsBands": ["Ariana Grande", "Billie Eilish"], "watchList": ["Barbie", "The Fashion Fund"]}',
  true,
  true
),
(
  'vikram.singh@example.com',
  '$2b$10$xQqVZ8K3lXKJ4X8vZ9xW5eF.WxJhZ6KpY9qHxW5eF.WxJhZ6KpY9q',
  'Vikram',
  'Singh',
  'Male',
  '1994-09-18',
  'Delhi',
  'Chandigarh',
  'https://randomuser.me/api/portraits/men/3.jpg',
  185,
  'Single',
  'No Pets',
  'Socially',
  'No',
  'Non-Vegetarian',
  'Moderately Religious',
  'Want Someday',
  'Dubai',
  '["Business", "Golf", "Cars", "Travel", "Wine"]',
  '@vikram_entrepreneur',
  'https://linkedin.com/in/vikramsingh',
  '["https://randomuser.me/api/portraits/men/3.jpg", "https://randomuser.me/api/portraits/men/13.jpg", "https://randomuser.me/api/portraits/men/23.jpg"]',
  '{"bio": "Entrepreneur and adventure seeker. Building dreams and exploring the world 🚀", "lifestyleImageUrls": ["https://images.unsplash.com/photo-1507679799987-c73779587ccf", "https://images.unsplash.com/photo-1552664730-d307ca884978", "https://images.unsplash.com/photo-1473496169904-658ba7c44d8a"], "profileQuestions": {"jobTitle": "Founder & CEO", "companyName": "Tech Ventures", "education": "IIM Ahmedabad", "educationLevel": "MBA", "sleepSchedule": "Flexible", "dateBill": "I will pay", "relationshipValues": ["Ambition", "Adventure"], "religion": "Sikh", "livingSituation": "Own Place", "languages": ["English", "Hindi", "Punjabi"]}, "movies": ["The Wolf of Wall Street", "The Social Network", "Iron Man"], "tvShows": ["Suits", "Billions"], "artistsBands": ["Drake", "The Weeknd"], "watchList": ["Top Gun Maverick", "Ferrari"]}',
  true,
  true
);

-- Display summary
SELECT 'Successfully inserted 6 sample users' AS status;
SELECT COUNT(*) as total_users FROM users;
SELECT first_name, last_name, email, gender, approval FROM users WHERE approval = true;
